# Generated by Django 5.2.1 on 2025-05-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabprofile',
            name='gitlab_host',
            field=models.CharField(blank=True, default='https://gitlab.com', max_length=255, null=True),
        ),
    ]
